name: release

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  mac_release:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Check out Git repository
        uses: actions/checkout@master

      - name: Setup Node.js environment
        uses: actions/setup-node@master
        with:
          node-version: 16.x
          cache: npm

      - run: npm ci
      - run: npm run build:mac
        shell: bash

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          path: release/*/*.*
          if-no-files-found: ignore
      - name: Create a release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: release/*/*.*

  windows_release:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Check out Git repository
        uses: actions/checkout@master

      - name: Setup Node.js environment
        uses: actions/setup-node@master
        with:
          node-version: 16.x
          cache: npm

      - run: npm ci
      - run: npm run build:win
        shell: bash

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          path: release/*/*.*
          if-no-files-found: ignore

      - name: Create a release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: release/*/*.*

  linux_release:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out Git repository
        uses: actions/checkout@master

      - name: Setup Node.js environment
        uses: actions/setup-node@master
        with:
          node-version: 16.x
          cache: npm

      - run: npm ci
      - run: npm run build:linux
        shell: bash

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          path: release/*/*.*
          if-no-files-found: ignore

      - name: Create a release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: release/*/*.*
