# Release 发行版本部署
## 多端部署
name: Build Release

on:
  push:
    tags:
      - v*

jobs:
  # Windows
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1
      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "18.x"
      # 复制环境变量文件
      - name: Copy .env.example
        run: cp .env.example .env
      # 安装项目依赖
      - name: Install Dependencies
        run: npm install
      # 构建 Electron App
      - name: Build Electron App for Windows
        run: npm run build:win || true
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      # 上传构建产物
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: SPlarer-Win
          if-no-files-found: ignore
          path: |
            dist/*.exe
            dist/*.msi
            dist/latest.yml
      # 创建 GitHub Release
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          if-no-files-found: ignore
          files: |
            dist/*.exe
            dist/*.msi
            dist/latest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  # Mac
  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1
      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "18.x"
      # 复制环境变量文件
      - name: Copy .env.example
        run: cp .env.example .env
      # 安装项目依赖
      - name: Install Dependencies
        run: npm install
      # 构建 Electron App
      - name: Build Electron App for macOS
        run: npm run build:mac || true
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      # 上传构建产物
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: SPlarer-Macos
          if-no-files-found: ignore
          path: |
            dist/*.dmg
            dist/*.zip
            dist/latest-mac.yml
      # 创建 GitHub Release
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          if-no-files-found: ignore
          files: |
            dist/*.dmg
            dist/*.zip
            dist/latest-mac.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  # Linux
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-22.04
    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1
      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "18.x"
      # 更新 Ubuntu 软件源
      - name: Ubuntu Update with sudo
        run: sudo apt-get update
      # 复制环境变量文件
      - name: Copy .env.example
        run: cp .env.example .env
      # 安装项目依赖
      - name: Install Dependencies
        run: npm install
      # 构建 Electron App
      - name: Build Electron App for Linux
        run: npm run build:linux || true
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      # 上传构建产物
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: SPlarer-Linux
          if-no-files-found: ignore
          path: |
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/latest-linux.yml
      # 创建 GitHub Release
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          if-no-files-found: ignore
          files: |
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/latest-linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
